# Generated by Django 5.1.5 on 2025-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة المقال'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة المنتج'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الخدمة'),
        ),
    ]
