"""
Django settings for palmsite project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
import os
import dj_database_url   # مكتبة لقراءة DATABASE_URL من المتغيرات

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n3ej-529nd_ofygu044*)w236=i8t((=to#8^imtu^f@z#p3lt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]  # مؤقتاً مفتوح لكل الهوستات


# Application definition
INSTALLED_APPS = [
    "jazzmin",   # واجهة الأدمين المحسّنة
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',   # التطبيق الرئيسي
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # لدعم تعدد اللغات
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'palmsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # مسار عام للقوالب
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,  # يبحث داخل كل تطبيق تلقائياً
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'palmsite.wsgi.application'


# Database (PostgreSQL from Render)
DATABASES = {
    'default': dj_database_url.config(
        default="postgresql://palmsite_db_user:4kntGkmzsL6ikHUGJEC9AltygQPdhcVK@dpg-d39rrire5dus73bnjisg-a.oregon-postgres.render.com/palmsite_db",
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'   # اللغة الأساسية للوحة التحكم
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # ملفات ثابتة عامة
STATIC_ROOT = BASE_DIR / "staticfiles"    # عند عمل collectstatic

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# إعدادات Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "لوحة الإدارة",
    "site_header": "مؤسسة النخيل والشبوك",
    "site_brand": "لوحة التحكم",
    "welcome_sign": "مرحباً بك في لوحة إدارة الموقع",
    "copyright": "© 2025 مؤسسة النخيل",

    # القوائم العلوية
    "topmenu_links": [
        {"name": "الرئيسية", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "الموقع", "url": "/", "new_window": True},
    ],

    # القائمة المنسدلة للمستخدم
    "usermenu_links": [
        {"name": "تواصل معنا", "url": "/contact", "new_window": True},
    ],

    # أيقونات التطبيقات
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.Service": "fas fa-tools",
        "main.Product": "fas fa-leaf",
        "main.BlogPost": "fas fa-blog",
    },

    # السماح بتخصيص الثيم من لوحة التحكم
    "show_ui_builder": True,
}
